### ISSUE TITLE
Unnecessary `T.unpack` <-> `T.pack` in the Haskell code

### ISSUE THREAD

**Issue by Vlix** [Airsequel/double-x-encoding#3]
I'm seeing [a few cases](https://github.com/Airsequel/double-x-encoding/blob/main/Haskell/source/DoubleXEncoding.hs#L303-L306) of unnecessary jumping to and from `String`, where everything could be done in `Text` using functions from the `Data.Text` module.

You can replace the
```hs
...
  & T.unpack
  & take 5
  <&> f
  & T.pack
...
```
with the [`T.map` function](https://hackage.haskell.org/package/text-2.1.1/docs/Data-Text.html#v:map) and make it:
```hs
...
  & T.take 5
  & T.map f
...
```

**Comment by ad-si** [comment]
Good catch! Thanks a lot!

I removed all unnecessary `T.pack` and `T.unpack` in 792c032.
